### ISSUE TITLE
Decide sampling strategy for countries and languages 

### ISSUE THREAD

**Issue by jilltxt** [MachineVisionUiB/GPT_stories#5]
Goal:
- range of cultures where English is a common language (native language/first language/primary language/official language/lingua franca
- add in culturally specific regions: Scotland, Northern-Irish, Welsh, English, Irish
- add languages: Nynorsk, bokmål, Akan, Sámi

@Tm-ui will check linguistics scholarship for common strategies, otherwise go with the 
- Top 10 Countries that Speak English as a Primary Language (by total population 2021)
- Top 10 English-Speaking Countries in the [World](https://worldpopulationreview.com/continents/world-population) (as primary or lingua franca 2021) 
from this page https://worldpopulationreview.com/country-rankings/english-speaking-countries

**Comment by SamInMotion** [comment]
Sampling Strategy
The sampling strategy proposed in this study is rooted in theoretical considerations and research questions, providing flexibility in selecting classifications independent of the sampling method (Rijkhoff & Bakker, 1998). This approach takes into account sample type, classification, academic domain, and sample size. It is important to note that larger numbers of variables necessitate larger samples (Buchstaller & Khattab, 2013).
 
A common method utilized in linguistic literature is systematic, proportional, or weighted sampling (Barratt et al., 2021; Buchstaller & Khattab, 2013; Zhang et al., 2023). This methodology addresses frequency bias concerns and enhances the quality of language representations. It involves dividing the total number of English speakers worldwide by the intended sample size, typically a specific geographical region with a population of English speakers, and arranging them in order of magnitude. This approach ensures the representation of geographically concentrated regions with English speakers, thereby considering the distribution of English speakers worldwide . Consequently, it facilitates the examination of the entire spectrum of the target population.
 
The steps involved in this sampling method are as follows:
1. Obtain data on the number of English speakers in different countries.
2. Calculate the total number of English speakers worldwide (Total).
3. Determine the weight (W) of each country using the formula:
   W = Number of English speakers in the country / Total.
4. Sort the countries based on their weights in descending order.
5. Select a representative group by choosing the top N countries with the highest weights.
 
From a cultural perspective, the approach can align with Braj Kachru's concept of three circles of English distribution (Kachru, 1990), allowing for the organization of data into three sets based on the weighted sample countries that fall within these circles. It is crucial to utilize datasets based on reliable sources such as Ethnologue, which is considered the most authoritative and comprehensive resource on languages and their speakers (Amano et al., 2014).


References
(Amano et al., 2014; Barratt et al., 2021; Buchstaller & Khattab, 2013; Kachru, 1990; Rijkhoff & Bakker, 1998; Zhang et al., 2023)

**Comment by jilltxt** [comment]
Thank you! This is very useful, and I like how structured it is. However, I think we don't need weighted samples as suggested in the last paragraph, because we are not studying actual English speakers but an AI model's "ideas" about stories, and because our goal is to compare "typical" generated stories for each nationality, not to find "the average story taking many cultures into account". 

We just need a list of the 10-15 "nationalities" (countries) where English is "most common". I guess following the five steps you suggest would achieve that in a transparent and replicable manner. Do you think it would be better to calculate this ourselves, using Enthnologue (if they have numbers of English speakers?) instead of just merging the two lists from World Population Review?
